import type { ToolcraftControlSchema, ToolcraftControlSectionSchema } from "@/toolcraft/runtime";

import {
  floorAmbient,
  floorAzimuth,
  floorBackground,
  floorBevel,
  floorColumns,
  floorDamping,
  floorDepth,
  floorElevation,
  floorFalloffs,
  floorGap,
  floorHaze,
  floorHeight,
  floorHue,
  floorLag,
  floorLightness,
  floorMass,
  floorOrbitPosition,
  floorOrbitUp,
  floorPatch,
  floorPatterns,
  floorRadius,
  floorRelief,
  floorSaturation,
  floorSeed,
  floorShade,
  floorSheen,
  floorStiffness,
} from "./floor-defaults";

const always = { mode: "always" } as const;

function slider(
  control: Extract<ToolcraftControlSchema, { type: "slider" }>,
): Extract<ToolcraftControlSchema, { type: "slider" }> {
  return control;
}

const responsive = {
  performanceReason: "Changes shading or motion without adding cubes or export pixels.",
  performanceRole: "responsiveness",
} as const;

export const floorControlSections: readonly ToolcraftControlSectionSchema[] = [
  {
    controls: {
      orbit: {
        applicability: always,
        defaultValue: {
          position: [floorOrbitPosition[0], floorOrbitPosition[1], floorOrbitPosition[2]],
          up: [floorOrbitUp[0], floorOrbitUp[1], floorOrbitUp[2]],
        },
        keyframeable: false,
        label: false,
        performanceReason: "Orbit changes the camera pose for the same cube field.",
        performanceRole: "responsiveness",
        target: "view.orbit",
        type: "orientationGizmo",
      },
      columns: slider({
        applicability: always,
        defaultValue: floorColumns.defaultValue,
        label: "Field count",
        max: floorColumns.max,
        min: floorColumns.min,
        performanceReason: "Column count is the number of instanced cubes drawn and simulated.",
        performanceRole: "workload",
        sliderValueKind: "discrete",
        step: floorColumns.step,
        target: "field.columns",
        type: "slider",
        unit: "cols",
        variant: "discrete",
      }),
      gap: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorGap.defaultValue,
        label: "Gap",
        max: floorGap.max,
        min: floorGap.min,
        sliderValueKind: "continuous",
        step: floorGap.step,
        target: "field.gap",
        type: "slider",
        variant: "continuous",
      }),
      bevel: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorBevel.defaultValue,
        label: "Bevel",
        max: floorBevel.max,
        min: floorBevel.min,
        sliderValueKind: "continuous",
        step: floorBevel.step,
        target: "field.bevel",
        type: "slider",
        variant: "continuous",
      }),
      floor: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorHeight.defaultValue,
        label: "Field height",
        max: floorHeight.max,
        min: floorHeight.min,
        sliderValueKind: "continuous",
        step: floorHeight.step,
        target: "field.floor",
        type: "slider",
        variant: "continuous",
      }),
      relief: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorRelief.defaultValue,
        label: "Relief",
        max: floorRelief.max,
        min: floorRelief.min,
        sliderValueKind: "continuous",
        step: floorRelief.step,
        target: "field.relief",
        type: "slider",
        variant: "continuous",
      }),
    },
    id: "squares",
    title: "Squares",
  },
  {
    controls: {
      pattern: {
        applicability: always,
        defaultValue: "patches",
        label: "Pattern",
        options: [
          { label: "Patches", value: floorPatterns[0] },
          { label: "Bands", value: floorPatterns[1] },
          { label: "Drift", value: floorPatterns[2] },
          { label: "Specks", value: floorPatterns[3] },
        ],
        ...responsive,
        target: "palette.pattern",
        type: "segmented",
      },
      hue: {
        ...responsive,
        applicability: always,
        defaultValue: [...floorHue.defaultValue],
        label: "Hue",
        max: floorHue.max,
        min: floorHue.min,
        sliderValueKind: "discrete",
        step: floorHue.step,
        target: "palette.hue",
        type: "rangeSlider",
        unit: "°",
        variant: "continuous",
      },
      saturation: {
        ...responsive,
        applicability: always,
        defaultValue: [...floorSaturation.defaultValue],
        label: "Saturation",
        max: floorSaturation.max,
        min: floorSaturation.min,
        sliderValueKind: "discrete",
        step: floorSaturation.step,
        target: "palette.saturation",
        type: "rangeSlider",
        unit: "%",
        variant: "continuous",
      },
      lightness: {
        ...responsive,
        applicability: always,
        defaultValue: [...floorLightness.defaultValue],
        label: "Lightness",
        max: floorLightness.max,
        min: floorLightness.min,
        sliderValueKind: "discrete",
        step: floorLightness.step,
        target: "palette.lightness",
        type: "rangeSlider",
        unit: "%",
        variant: "continuous",
      },
      patch: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorPatch.defaultValue,
        label: "Patch",
        max: floorPatch.max,
        min: floorPatch.min,
        sliderValueKind: "continuous",
        step: floorPatch.step,
        target: "palette.patch",
        type: "slider",
        variant: "continuous",
      }),
      seed: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorSeed.defaultValue,
        label: "Seed",
        max: floorSeed.max,
        min: floorSeed.min,
        sliderValueKind: "discrete",
        step: floorSeed.step,
        target: "palette.seed",
        type: "slider",
        variant: "continuous",
      }),
      shuffle: {
        actions: [{ icon: "shuffle", label: "Shuffle", value: "shuffle" }],
        applicability: always,
        defaultValue: null,
        label: "Arrangement",
        orderRole: "action",
        performanceReason: "Shuffle advances the existing seed without adding cubes.",
        performanceRole: "responsiveness",
        target: "palette.shuffle",
        type: "actions",
      },
    },
    id: "palette",
    title: "Palette",
  },
  {
    controls: {
      falloff: {
        applicability: always,
        defaultValue: "soft",
        label: "Falloff",
        options: [
          { label: "Soft", value: floorFalloffs[0] },
          { label: "Linear", value: floorFalloffs[1] },
          { label: "Tight", value: floorFalloffs[2] },
          { label: "Wide", value: floorFalloffs[3] },
        ],
        ...responsive,
        target: "push.falloff",
        type: "segmented",
      },
      radius: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorRadius.defaultValue,
        label: "Radius",
        max: floorRadius.max,
        min: floorRadius.min,
        sliderValueKind: "discrete",
        step: floorRadius.step,
        target: "push.radius",
        type: "slider",
        unit: "px",
        variant: "continuous",
      }),
      depth: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorDepth.defaultValue,
        label: "Depth",
        max: floorDepth.max,
        min: floorDepth.min,
        sliderValueKind: "continuous",
        step: floorDepth.step,
        target: "push.depth",
        type: "slider",
        variant: "continuous",
      }),
      stiffness: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorStiffness.defaultValue,
        label: "Stiffness",
        max: floorStiffness.max,
        min: floorStiffness.min,
        sliderValueKind: "discrete",
        step: floorStiffness.step,
        target: "push.stiffness",
        type: "slider",
        variant: "continuous",
      }),
      damping: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorDamping.defaultValue,
        label: "Damping",
        max: floorDamping.max,
        min: floorDamping.min,
        sliderValueKind: "continuous",
        step: floorDamping.step,
        target: "push.damping",
        type: "slider",
        variant: "continuous",
      }),
      mass: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorMass.defaultValue,
        label: "Mass",
        max: floorMass.max,
        min: floorMass.min,
        sliderValueKind: "continuous",
        step: floorMass.step,
        target: "push.mass",
        type: "slider",
        variant: "continuous",
      }),
      lag: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorLag.defaultValue,
        label: "Lag",
        max: floorLag.max,
        min: floorLag.min,
        sliderValueKind: "discrete",
        step: floorLag.step,
        target: "push.lag",
        type: "slider",
        unit: "ms",
        variant: "continuous",
      }),
    },
    description: "The cursor presses cubes down. They spring back after it leaves, and push edits replay a short center press.",
    id: "push",
    title: "Push",
  },
  {
    controls: {
      azimuth: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorAzimuth.defaultValue,
        label: "Azimuth",
        max: floorAzimuth.max,
        min: floorAzimuth.min,
        sliderValueKind: "discrete",
        step: floorAzimuth.step,
        target: "light.azimuth",
        type: "slider",
        unit: "°",
        variant: "continuous",
      }),
      elevation: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorElevation.defaultValue,
        label: "Elevation",
        max: floorElevation.max,
        min: floorElevation.min,
        sliderValueKind: "discrete",
        step: floorElevation.step,
        target: "light.elevation",
        type: "slider",
        unit: "°",
        variant: "continuous",
      }),
      shade: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorShade.defaultValue,
        label: "Shade",
        max: floorShade.max,
        min: floorShade.min,
        sliderValueKind: "continuous",
        step: floorShade.step,
        target: "light.shade",
        type: "slider",
        variant: "continuous",
      }),
      ambient: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorAmbient.defaultValue,
        label: "Ambient",
        max: floorAmbient.max,
        min: floorAmbient.min,
        sliderValueKind: "continuous",
        step: floorAmbient.step,
        target: "light.ambient",
        type: "slider",
        variant: "continuous",
      }),
      sheen: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorSheen.defaultValue,
        label: "Sheen",
        max: floorSheen.max,
        min: floorSheen.min,
        sliderValueKind: "continuous",
        step: floorSheen.step,
        target: "light.sheen",
        type: "slider",
        variant: "continuous",
      }),
      haze: slider({
        ...responsive,
        applicability: always,
        defaultValue: floorHaze.defaultValue,
        label: "Haze",
        max: floorHaze.max,
        min: floorHaze.min,
        sliderValueKind: "continuous",
        step: floorHaze.step,
        target: "light.haze",
        type: "slider",
        variant: "continuous",
      }),
    },
    id: "light",
    title: "Light",
  },
  {
    controls: {
      include: {
        applicability: always,
        defaultValue: true,
        label: "Include",
        performanceReason: "The switch changes whether cube pixels pick up the floor color.",
        performanceRole: "responsiveness",
        target: "export.includeBackground",
        type: "switch",
      },
      floor: {
        applicability: always,
        defaultValue: floorBackground,
        label: "Floor",
        performanceReason: "The floor color tints cube faces and fills included exports.",
        performanceRole: "responsiveness",
        target: "appearance.background",
        type: "color",
      },
    },
    id: "background",
    title: "Background",
  },
];
